### ISSUE TITLE
Could you please share information about your project?

### ISSUE THREAD

**Issue by DmytroLebed** [wataniguchi/EV3RT#16]
Hello.
I'm Dmytro Lebed.
I am from Ukraine, a small town in the Zaporozhye region.

As a hobby in 2018, I created and lead a robotics club for my son and his friends.
In the first place for me is educational robotics, no commerce, classes are completely free.

In the 2018/19 academic year, we got acquainted with the EV3 platform and worked in EV3-G, then, in the summer we worked in MicroPythonV1, we liked the language, but there were problems.

We studied and worked on BasicPlus in the Clever IDE for the 2019/20 academic year.

Now my son is 12 years old, he really likes C++, and I am looking for a language to study next year. I am considering ev3dev cpp, c4ev3, evCpp, and recently we discovered EV3RT.

I was able to set up my development environment for VS code + EV3RT.
I did some tests and really liked the performance of the EV3RT.

Unfortunately, very few people program EV3 in C++ and there is very little information on the internet.
I am preparing an educational program for children for the academic year, there is a very lack of information about programming on ev3 C++, examples of programs.

On github, I found your EV3RT project, it is the only one with an object-oriented structure. I am trying to understand how to solve our tasks using this example.

Could you please share information about your project, which version of ev3rt-hrp are you using, for which competitions is it?

Thanks in advance,
Dmytro Lebed.

https://www.facebook.com/dmytro.lebed
https://www.facebook.com/optimum.robotics.team

**Comment by wataniguchi** [comment]
Thanks for your message, Dmytro.
Version of EV3RT we use is HRP3 version 3.0.0.
The competition we are in is the following:
https://www.etrobo.jp

This year unfortunately, because of the COVID epidemic, the competition is done via software simulator, not the use of actual MindStorm device.  Thus, the code on GitHum may not be compatible with the device.  Nonetheless, please feel free to learn from the published code if useful.

Enjoy your project with the kids!

Regards,
Wataru Taniguchi

**Comment by DmytroLebed** [comment]
Thanks for answers.

A couple of questions, if I may.

1.Where can I get HRP3 version 3.0.0 for EV3? On the official website only ev3rt-hrp3 - HRP3 version 1.0 

2.I tried the HRP3, the problem is - during the execution of the program it often turns off, then turns on the color sensors.
We are starting a new academic year in October and I would like to decide which core to work with HRP2 or HRP3.

Regards,
Dmytro Lebed.

**Comment by wataniguchi** [comment]
1. Obtained as a part of etrobo all-in-one installer/builder/launcher environment at the following URL:
  https://github.com/ETrobocon/etrobo
2. Such symptoms are not observed with the above-mentioned all-in-one environment.  Not at least in simulator.
